/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sequencealignment;

/**
 *
 * @author Hannah Coleman
 */
public class AlignmentView extends javax.swing.JPanel {

    /**
     * Creates new form AlignmentView
     */
    public AlignmentView(DPModel model) {
        initComponents();
        this.model = model;
        updateAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alignment = new javax.swing.JLabel();
        alignedSeq1 = new javax.swing.JLabel();
        alignedSeq2 = new javax.swing.JLabel();
        matches = new javax.swing.JLabel();

        setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        alignment.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        alignment.setText("jLabel1");

        alignedSeq1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        alignedSeq1.setText("jLabel2");

        alignedSeq2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        alignedSeq2.setText("jLabel3");

        matches.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        matches.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alignment)
                    .addComponent(alignedSeq1)
                    .addComponent(alignedSeq2)
                    .addComponent(matches))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alignment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alignedSeq1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(matches)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alignedSeq2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void updateAll()
    {
        String s = "";
        
        if (model.alignedSeq1.length() == model.alignedSeq2.length())
        {
            for (int i = 0; i < model.alignedSeq1.length(); i++)
            {
                if (model.alignedSeq1.charAt(i) == model.alignedSeq2.charAt(i))
                {
                    s = s + "|";
                }
                else
                {
                    s = s + " ";
                }
            }
            
        }
        else
        {
            throw new IllegalStateException(
                    "Sequences differ in length after alignment.");
        }
        
        alignment.setText(model.alignment.toString());
        alignedSeq1.setText(model.alignedSeq1.toString());
        alignedSeq2.setText(model.alignedSeq2.toString());
        matches.setText(s);
    }
    
    // Variables declaration - can modify
    private DPModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alignedSeq1;
    private javax.swing.JLabel alignedSeq2;
    private javax.swing.JLabel alignment;
    private javax.swing.JLabel matches;
    // End of variables declaration//GEN-END:variables
}
