/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sequencealignment;


/**
 *
 * @author Hannah Coleman
 */
public class MainController extends javax.swing.JFrame {

    /**
     * Creates new form MainController
     */
    public MainController() {
        this.model = new DPModel("", "");
        this.gridView = new GridView(model);
        this.alignmentView = new AlignmentView(model);
        gridViewport = new javax.swing.JViewport();
        alignmentViewport = new javax.swing.JViewport();
        gridViewport.setView(gridView);
        alignmentViewport.setView(alignmentView);
        
        initComponents();
        
        /*
        JFrame f = new JFrame();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setSize(500,500);
        
        JFrame g = new JFrame();
        g.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        g.setSize(295,160);
        
        f.add(gridView);
        g.add(alignmentView);
        f.setVisible(true);
        g.setVisible(true);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        sequence1InputField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sequence2InputField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        fillJumpBackButton = new javax.swing.JButton();
        fillStepBackButton = new javax.swing.JButton();
        fillStepForwardButton = new javax.swing.JButton();
        fillJumpForwardButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        traceJumpBackButton = new javax.swing.JButton();
        traceStepBackButton = new javax.swing.JButton();
        traceStepForwardButton = new javax.swing.JButton();
        traceJumpForwardButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainControllerMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Select algorithm:");

        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox1.setMaximumRowCount(3);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Longest Common Subsequence", "Global Alignment", "Local Alignment" }));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Sequence 1");

        sequence1InputField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sequence1InputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sequenceInputFieldFocusLost(evt);
            }
        });
        sequence1InputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sequence1InputFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Sequence 2");

        sequence2InputField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sequence2InputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sequenceInputFieldFocusLost(evt);
            }
        });
        sequence2InputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sequence2InputFieldActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Score Table");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Show all arrows");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        fillJumpBackButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fillJumpBackButton.setText("<<");
        fillJumpBackButton.setToolTipText("Jump Backward");
        fillJumpBackButton.setEnabled(false);
        fillJumpBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillJumpBackButtonActionPerformed(evt);
            }
        });

        fillStepBackButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fillStepBackButton.setText("<");
        fillStepBackButton.setToolTipText("Step Backward");
        fillStepBackButton.setEnabled(false);
        fillStepBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillStepBackButtonActionPerformed(evt);
            }
        });

        fillStepForwardButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fillStepForwardButton.setText(">");
        fillStepForwardButton.setToolTipText("Step Forward");
        fillStepForwardButton.setEnabled(false);
        fillStepForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillStepForwardButtonActionPerformed(evt);
            }
        });

        fillJumpForwardButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fillJumpForwardButton.setText(">>");
        fillJumpForwardButton.setToolTipText("Jump Forward");
        fillJumpForwardButton.setEnabled(false);
        fillJumpForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillJumpForwardButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.setToolTipText("");
        clearButton.setEnabled(false);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewport(gridViewport);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jRadioButton1.setText("Linear Gap");
        jRadioButton1.setEnabled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jRadioButton2.setText("Affine Gap");
        jRadioButton2.setEnabled(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Longest Common Subsequence");

        jScrollPane2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(295, 82));
        jScrollPane2.setRequestFocusEnabled(false);
        jScrollPane2.setViewport(alignmentViewport);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Create, edit, or view score table:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Fill scores and directions:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Trace path:");

        traceJumpBackButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        traceJumpBackButton.setText("<<");
        traceJumpBackButton.setToolTipText("Jump Backward");
        traceJumpBackButton.setEnabled(false);
        traceJumpBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traceJumpBackButtonActionPerformed(evt);
            }
        });

        traceStepBackButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        traceStepBackButton.setText("<");
        traceStepBackButton.setToolTipText("Step Backward");
        traceStepBackButton.setEnabled(false);
        traceStepBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traceStepBackButtonActionPerformed(evt);
            }
        });

        traceStepForwardButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        traceStepForwardButton.setText(">");
        traceStepForwardButton.setToolTipText("Step Forward");
        traceStepForwardButton.setEnabled(false);
        traceStepForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traceStepForwardButtonActionPerformed(evt);
            }
        });

        traceJumpForwardButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        traceJumpForwardButton.setText(">>");
        traceJumpForwardButton.setToolTipText("Jump Forward");
        traceJumpForwardButton.setEnabled(false);
        traceJumpForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traceJumpForwardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(sequence2InputField)
                    .addComponent(sequence1InputField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fillJumpBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fillStepBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fillStepForwardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fillJumpForwardButton))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(traceJumpBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(traceStepBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(traceStepForwardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(traceJumpForwardButton))
                    .addComponent(clearButton)
                    .addComponent(jCheckBox1))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sequence1InputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sequence2InputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fillJumpBackButton)
                            .addComponent(fillStepBackButton)
                            .addComponent(fillStepForwardButton)
                            .addComponent(fillJumpForwardButton))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(traceJumpBackButton)
                            .addComponent(traceStepBackButton)
                            .addComponent(traceStepForwardButton)
                            .addComponent(traceJumpForwardButton))
                        .addGap(26, 26, 26)
                        .addComponent(clearButton)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(37, 37, 37))
        );

        fillJumpBackButton.getAccessibleContext().setAccessibleName("Jump Backward");
        fillStepBackButton.getAccessibleContext().setAccessibleName("Step Backward");
        fillStepForwardButton.getAccessibleContext().setAccessibleName("Step Forward");
        fillJumpForwardButton.getAccessibleContext().setAccessibleName("Jump Forward");
        traceJumpBackButton.getAccessibleContext().setAccessibleName("Jump Backward");
        traceStepBackButton.getAccessibleContext().setAccessibleName("Step Backward");
        traceStepForwardButton.getAccessibleContext().setAccessibleName("Step Forward");
        traceJumpForwardButton.getAccessibleContext().setAccessibleName("Step Forward");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sequence2InputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sequence2InputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sequence2InputFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fillJumpBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillJumpBackButtonActionPerformed
        model.clearAll();
        
        gridView.updateAll();
        
        fillStepForwardButton.setEnabled(true);
        fillJumpForwardButton.setEnabled(true);
        fillStepBackButton.setEnabled(false);
        fillJumpBackButton.setEnabled(false);
        traceStepForwardButton.setEnabled(false);
        traceJumpForwardButton.setEnabled(false);
        traceStepBackButton.setEnabled(false);
        traceJumpBackButton.setEnabled(false);
    }//GEN-LAST:event_fillJumpBackButtonActionPerformed

    private void fillJumpForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillJumpForwardButtonActionPerformed
        model.fillRemaining();
        
        gridView.updateAll();
        
        fillStepForwardButton.setEnabled(false);
        fillJumpForwardButton.setEnabled(false);
        fillStepBackButton.setEnabled(true);
        fillJumpBackButton.setEnabled(true);
        traceStepForwardButton.setEnabled(true);
        traceJumpForwardButton.setEnabled(true);
        traceStepBackButton.setEnabled(false);
        traceJumpBackButton.setEnabled(false);
    }//GEN-LAST:event_fillJumpForwardButtonActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void traceStepForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traceStepForwardButtonActionPerformed
        model.traceCell();
        
        gridView.updateAll();
        alignmentView.updateAll();
        
        if (model.x == 0 && model.y == 0)
        {
            traceStepForwardButton.setEnabled(false);
            traceJumpForwardButton.setEnabled(false);
        }
        
        fillStepBackButton.setEnabled(false);
        fillJumpBackButton.setEnabled(false);
        traceStepBackButton.setEnabled(true);
        traceJumpBackButton.setEnabled(true);
        
        
    }//GEN-LAST:event_traceStepForwardButtonActionPerformed

    private void traceJumpForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traceJumpForwardButtonActionPerformed
        model.traceRemaining();
        
        gridView.updateAll();
        alignmentView.updateAll();
        
        //fillStepForwardButton.setEnabled(false);
        //fillJumpForwardButton.setEnabled(false);
        fillStepBackButton.setEnabled(false);
        fillJumpBackButton.setEnabled(false);
        traceStepForwardButton.setEnabled(false);
        traceJumpForwardButton.setEnabled(false);
        traceStepBackButton.setEnabled(true);
        traceJumpBackButton.setEnabled(true);
    }//GEN-LAST:event_traceJumpForwardButtonActionPerformed

    private void fillStepBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillStepBackButtonActionPerformed
        model.clearCellAndDecrement();
        
        gridView.updateAll();
        
        // if beginning reached, disable back fill buttons
        if (model.x == 1 && model.y == 1)
        {
            fillStepBackButton.setEnabled(false);
            fillJumpBackButton.setEnabled(false);
        }
        
        fillStepForwardButton.setEnabled(true);
        fillJumpForwardButton.setEnabled(true);
        traceStepForwardButton.setEnabled(false);
        traceJumpForwardButton.setEnabled(false);
    }//GEN-LAST:event_fillStepBackButtonActionPerformed

    private void fillStepForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillStepForwardButtonActionPerformed
        model.fillCellAndIncrement();

        gridView.updateAll();
        
        // if end reached, reset coordinates and disable forward buttons
        if (model.x == model.sequence2.length() && model.y == model.sequence1.length()
                && model.path[model.y][model.x] != 0)
        {
            fillStepForwardButton.setEnabled(false);
            fillJumpForwardButton.setEnabled(false);
            traceStepForwardButton.setEnabled(true);
            traceJumpForwardButton.setEnabled(true);
        }
        
        // enable fill back buttons
        fillStepBackButton.setEnabled(true);
        fillJumpBackButton.setEnabled(true);
        
    }//GEN-LAST:event_fillStepForwardButtonActionPerformed

    private void traceJumpBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traceJumpBackButtonActionPerformed
        model.untraceRemaining();
        
        gridView.updateAll();
        alignmentView.updateAll();
        
        fillStepForwardButton.setEnabled(false);
        fillJumpForwardButton.setEnabled(false);
        fillStepBackButton.setEnabled(true);
        fillJumpBackButton.setEnabled(true);
        traceStepForwardButton.setEnabled(true);
        traceJumpForwardButton.setEnabled(true);
        traceStepBackButton.setEnabled(false);
        traceJumpBackButton.setEnabled(false);
        
    }//GEN-LAST:event_traceJumpBackButtonActionPerformed

    private void traceStepBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traceStepBackButtonActionPerformed
        model.untraceCell();
        
        gridView.updateAll();
        alignmentView.updateAll();
        
        if (model.x == model.sequence2.length() && model.y == model.sequence1.length())
        {
            fillStepBackButton.setEnabled(true);
            fillJumpBackButton.setEnabled(true);
            traceStepBackButton.setEnabled(false);
            traceJumpBackButton.setEnabled(false);
        }
        
        traceStepForwardButton.setEnabled(true);
        traceJumpForwardButton.setEnabled(true);
        
        
    }//GEN-LAST:event_traceStepBackButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        model.clearAll();
        
        gridView.updateAll();
        alignmentView.updateAll();
        
        fillStepForwardButton.setEnabled(true);
        fillJumpForwardButton.setEnabled(true);
        fillStepBackButton.setEnabled(false);
        fillJumpBackButton.setEnabled(false);
        traceStepForwardButton.setEnabled(false);
        traceJumpForwardButton.setEnabled(false);
        traceStepBackButton.setEnabled(false);
        traceJumpBackButton.setEnabled(false);
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void sequenceInputFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sequenceInputFieldFocusLost
        String text1 = sequence1InputField.getText();
        String text2 = sequence2InputField.getText();
        if (!(text1.equals(model.sequence1) && text2.equals(model.sequence2))
                && text1.length() > 0 && text2.length() > 0)
        {
            model = new DPModel(text1, text2);
            gridView = new GridView(model);
            alignmentView = new AlignmentView(model);
            gridViewport.setView(gridView);
            alignmentViewport.setView(alignmentView);
            fillStepForwardButton.setEnabled(true);
            fillJumpForwardButton.setEnabled(true);
            fillStepBackButton.setEnabled(false);
            fillJumpBackButton.setEnabled(false);
            traceStepForwardButton.setEnabled(false);
            traceJumpForwardButton.setEnabled(false);
            traceStepBackButton.setEnabled(false);
            traceJumpBackButton.setEnabled(false);
            clearButton.setEnabled(true);
        }
    }//GEN-LAST:event_sequenceInputFieldFocusLost

    private void sequence1InputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sequence1InputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sequence1InputFieldActionPerformed

    private void mainControllerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainControllerMousePressed
        requestFocus();
    }//GEN-LAST:event_mainControllerMousePressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainController().setVisible(true);
            }
        });
    }

    // Variables declaration - can be modified
    private DPModel model;
    private GridView gridView;
    private AlignmentView alignmentView;
    private javax.swing.JViewport gridViewport;
    private javax.swing.JViewport alignmentViewport;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton fillJumpBackButton;
    private javax.swing.JButton fillJumpForwardButton;
    private javax.swing.JButton fillStepBackButton;
    private javax.swing.JButton fillStepForwardButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField sequence1InputField;
    private javax.swing.JTextField sequence2InputField;
    private javax.swing.JButton traceJumpBackButton;
    private javax.swing.JButton traceJumpForwardButton;
    private javax.swing.JButton traceStepBackButton;
    private javax.swing.JButton traceStepForwardButton;
    // End of variables declaration//GEN-END:variables
}
